/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import entidades.articulos;
import logica.logArticulo;

/**
 *
 * @author Allan
 */
public class frmArticulo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmArticulo
     */
    public frmArticulo() {
        initComponents();
        this.refrescarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cbCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtRegistros = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Articulos");

        jLabel1.setText("Marca");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Categoria");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Precio unitario");

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronico", "Ropa", "Carpinteria", "Jardineria", "Ferreteria" }));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        dtRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Articulo", "Marca", "Descripcion", "Categoria", "Cantidad", "Precio"
            }
        ));
        dtRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dtRegistros);

        jLabel7.setText("Articulo");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(84, 84, 84)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtCantidad)
                            .addComponent(txtDescripcion)
                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(jLabel7)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addGap(22, 22, 22)
                                .addComponent(btnEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      private void refrescarTabla(){
        TableModel tablaModel = this.completarTableModel();
        dtRegistros.setModel(tablaModel);
    }
    private TableModel completarTableModel(){
        
       try {
        logArticulo logArticulo = new logArticulo();
        List<articulos>  miLista = logArticulo.todosArticulos();
        Object[] columnas = new Object[]{"ID", "Articulo", "Marca","Descripcion","Categoria","Cantidad","Precio"};
        Object[][] datos = new Object[miLista.size()][columnas.length];


        for (int i = 0; i < miLista.size(); i++) {
            datos[i][0] = miLista.get(i).getId();
            datos[i][1] = miLista.get(i).getNombre();
            datos[i][2] = miLista.get(i).getMarca();
            datos[i][3] = miLista.get(i).getDescripcion();
            datos[i][4] = miLista.get(i).getCategoria();
            datos[i][5] = miLista.get(i).getCantidad();
            datos[i][6] = miLista.get(i).getPrecioUnitario();
            
        }
        DefaultTableModel model = new DefaultTableModel(datos, columnas);
        return model;
       } catch (Exception e) {
        System.out.println(e);
       }

        return null;
    }
    private void dtRegistrosMouseClicked(java.awt.event.MouseEvent evt) {                                         
        this.mousePressed();
    }  
    private void mousePressed(){
        txtId.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),0).toString());
        txtNombre.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),1).toString());
        txtMarca.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),2).toString());
        txtDescripcion.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),3).toString());
        txtCantidad.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),5).toString());
        txtPrecioUnitario.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),6).toString());
        
    }









    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe llenar el id", "Falta informacion", JOptionPane.WARNING_MESSAGE);
        } else {
            logArticulo logArticulo = new logArticulo();
            articulos articulos = new articulos();
            articulos=logArticulo.buscarArticulos(Integer.parseInt(txtId.getText()));
            if (articulos==null) {
                JOptionPane.showMessageDialog(new JFrame(), "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                txtId.setText(String.valueOf(articulos.getId()));
                txtMarca.setText(articulos.getMarca());
                txtDescripcion.setText(articulos.getDescripcion());
                cbCategoria.setSelectedItem(articulos.getCategoria());
                txtCantidad.setText(String.valueOf(articulos.getCantidad()));
                txtNombre.setText(articulos.getNombre());
                txtPrecioUnitario.setText(String.valueOf(articulos.getPrecioUnitario()));
            }

        }
      

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
      if (txtMarca.getText().isEmpty()||txtDescripcion.getText().isEmpty()||txtCantidad.getText().isEmpty()||txtPrecioUnitario.getText().isEmpty()||txtNombre.getText().isEmpty()) {
        JOptionPane.showMessageDialog(new JFrame(), "Debe llenar todos los campos", "Falta informacion", JOptionPane.WARNING_MESSAGE);
      } else {
        articulos articulos = new articulos();
        logArticulo logArticulo = new logArticulo();
        articulos.setNombre(txtNombre.getText());
        articulos.setMarca(txtMarca.getText());
        articulos.setDescripcion(txtDescripcion.getText());
        articulos.setCategoria(String.valueOf( cbCategoria.getSelectedItem()));
        articulos.setCantidad(Integer.parseInt(txtCantidad.getText()));
        articulos.setPrecioUnitario(Double.parseDouble(txtPrecioUnitario.getText()));
        if (logArticulo.crearArticulo(articulos)) {
            JOptionPane.showMessageDialog(new JFrame(), "Se guardo correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            this.refrescarTabla();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
        }
      }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
         if (txtMarca.getText().isEmpty()||txtDescripcion.getText().isEmpty()||txtCantidad.getText().isEmpty()||txtPrecioUnitario.getText().isEmpty()||txtId.getText().isEmpty()||txtNombre.getText().isEmpty()) {
        JOptionPane.showMessageDialog(new JFrame(), "Debe llenar todos los campos", "Falta informacion", JOptionPane.WARNING_MESSAGE);
      } else {
        articulos articulos = new articulos();
        logArticulo logArticulo = new logArticulo();
        articulos.setId(Integer.parseInt(txtId.getText()));
        articulos.setNombre(txtNombre.getText());
        articulos.setMarca(txtMarca.getText());
        articulos.setDescripcion(txtDescripcion.getText());
        articulos.setCategoria(String.valueOf( cbCategoria.getSelectedItem()));
        articulos.setCantidad(Integer.parseInt(txtCantidad.getText()));
        articulos.setPrecioUnitario(Double.parseDouble(txtPrecioUnitario.getText()));
        if (logArticulo.actualizarArticulo(articulos)) {
            JOptionPane.showMessageDialog(new JFrame(), "Se actualizo correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            this.refrescarTabla();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
        }
      }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe ingresar un id", "Falta informacion", JOptionPane.WARNING_MESSAGE);
        } else {
            logArticulo logArticulo = new logArticulo();
            if (logArticulo.eliminarArticulo(Integer.parseInt(txtId.getText()))) {
                JOptionPane.showMessageDialog(new JFrame(), "Se elimino correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                this.refrescarTabla();
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Se elimino correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JTable dtRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioUnitario;
    // End of variables declaration//GEN-END:variables
}
