/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import entidades.cliente;
import logica.logCliente;

/**
 *
 * @author Allan
 */
public class frmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCliente
     */
    public frmCliente() {
        initComponents();
        this.refrescarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtRegistros = new javax.swing.JTable();
        tnBuscar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Telefono");

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        dtRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellidos", "Telefono"
            }
        ));
        dtRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dtRegistros);

        tnBuscar.setText("Buscar");
        tnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnBuscarActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCedula)
                    .addComponent(txtNombre)
                    .addComponent(txtApellidos)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tnBuscar))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrear))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed
    private void refrescarTabla(){
        TableModel tablaModel = this.completarTableModel();
        dtRegistros.setModel(tablaModel);
    }

    private TableModel completarTableModel(){
        try {
            logCliente logCliente = new logCliente();
            List<cliente> miLista = logCliente.todosClientes();
            Object[] columnas = new Object[]{"Cédula", "Nombre", "Apellidos","Telefono"};
            Object[][] datos = new Object[miLista.size()][columnas.length];
            for (int i = 0; i < miLista.size(); i++) {
                datos[i][0] = miLista.get(i).getCedula();
                datos[i][1] = miLista.get(i).getNombre();
                datos[i][2] = miLista.get(i).getApellidos();
                datos[i][3] = miLista.get(i).getTelefono();
            }

            DefaultTableModel model = new DefaultTableModel(datos, columnas);
            return model;
            
        } catch (Exception e) {
            System.out.println(e);
        }
        return null;
    }
    private void dtRegistrosMouseClicked(java.awt.event.MouseEvent evt) {                                         
        this.mousePressed();
    }  
    private void mousePressed(){
        txtCedula.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),0).toString());
        txtNombre.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),1).toString());
        txtApellidos.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),2).toString());
        txtTelefono.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),3).toString());
        
    }















    private void tnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnBuscarActionPerformed
        
        if (txtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe llenar todos los campos", "Falta informacion", JOptionPane.WARNING_MESSAGE);
        } else {
            logCliente logCliente = new logCliente();
            cliente cliente = new cliente();
            cliente = logCliente.consultarCliente(txtCedula.getText());
            if (cliente == null) {
                JOptionPane.showMessageDialog(new JFrame(), "No se encontro el cliente", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                txtCedula.setText(cliente.getCedula());
                txtNombre.setText(cliente.getNombre());
                txtApellidos.setText(cliente.getApellidos());
                txtTelefono.setText(cliente.getTelefono());
                
            }
        }
    }//GEN-LAST:event_tnBuscarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (txtCedula.getText().isEmpty()||txtNombre.getText().isEmpty()||txtApellidos.getText().isEmpty()||txtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe llenar todos los campos", "Falta informacion", JOptionPane.WARNING_MESSAGE);
        } else {
            cliente cliente = new cliente();
            logCliente logCliente = new logCliente();
            cliente.setCedula(txtCedula.getText());
            cliente.setNombre(txtNombre.getText());
            cliente.setApellidos(txtApellidos.getText());
            cliente.setTelefono(txtTelefono.getText());
            if (logCliente.crearCliente(cliente)) {
                JOptionPane.showMessageDialog(new JFrame(), "Se guardo correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                this.refrescarTabla();
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (txtCedula.getText().isEmpty()||txtNombre.getText().isEmpty()||txtApellidos.getText().isEmpty()||txtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe llenar todos los campos", "Falta informacion", JOptionPane.WARNING_MESSAGE);
        } else {
            cliente cliente = new cliente();
            logCliente logCliente = new logCliente();
            cliente.setCedula(txtCedula.getText());
            cliente.setNombre(txtNombre.getText());
            cliente.setApellidos(txtApellidos.getText());
            cliente.setTelefono(txtTelefono.getText());
            if (logCliente.actualizarCliente(cliente)) {
                JOptionPane.showMessageDialog(new JFrame(), "Se actualizo correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                this.refrescarTabla();
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe llenar todos los campos", "Falta informacion", JOptionPane.WARNING_MESSAGE);
        } else {
            logCliente logCliente = new logCliente();
      
            if (logCliente.eliminarCliente(txtCedula.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Se elimino correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                this.refrescarTabla();
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JTable dtRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tnBuscar;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
