/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import entidades.articulos;
import logica.logArticulo;
import logica.logCalculos;

/**
 *
 * @author Allan
 */
public class frmInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmInventario
     */
    public frmInventario() {
        initComponents();
        this.completarTableModel();
           this.refrescarTabla();
           this.llenarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dtRegistros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbArticulos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbPrecios = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inventario");
        setToolTipText("");

        dtRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Articulo", "Marca", "Descripcion", "Categoria", "Cantidad", "Precio "
            }
        ));
        dtRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(dtRegistros);

        jLabel1.setText("Inventario");

        jLabel2.setText("Total de articulos:");

        lbArticulos.setText("Total");

        jLabel3.setText("Total Precios:");

        lbPrecios.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrecios)
                    .addComponent(lbArticulos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(425, 425, 425))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbArticulos))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbPrecios))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void refrescarTabla(){
        TableModel tablaModel = this.completarTableModel();
        dtRegistros.setModel(tablaModel);
    }
    private TableModel completarTableModel(){
        try {
            logArticulo logArticulo = new logArticulo();
            List<articulos> miLista = logArticulo.todosArticulos();
            Object[] columnas = new Object[]{"ID", "Articulo", "Marca","Descripcion","Categoria","Cantidad","Precio"};
            Object[][] datos = new Object[miLista.size()][columnas.length];
            for (int i = 0; i < miLista.size(); i++) {
                datos[i][0] = miLista.get(i).getId();
                datos[i][1] = miLista.get(i).getNombre();
                datos[i][2] = miLista.get(i).getMarca();
                datos[i][3] = miLista.get(i).getDescripcion();
                datos[i][4] = miLista.get(i).getCategoria();
                datos[i][5] = miLista.get(i).getCantidad();
                datos[i][6] = miLista.get(i).getPrecioUnitario();
            }
            DefaultTableModel model = new DefaultTableModel(datos, columnas);
            return model;
            
        } catch (Exception e) {
            System.out.println(e);
        }
        return null;
    }
    void llenarDatos(){
        logCalculos logCalculos = new logCalculos();
        logArticulo logArticulo = new logArticulo();
        List<articulos> miLista = logArticulo.todosArticulos();
        lbArticulos.setText(String.valueOf(logCalculos.totalArticulos(miLista)));
        lbPrecios.setText(String.valueOf(logCalculos.totalPrecios(miLista)));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dtRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbArticulos;
    private javax.swing.JLabel lbPrecios;
    // End of variables declaration//GEN-END:variables
}
