/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import javax.swing.UIManager;

/**
 *
 * @author Allan
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Administrar = new javax.swing.JMenu();
        opCrearUsuario = new javax.swing.JMenuItem();
        opCrearCliente = new javax.swing.JMenuItem();
        opCrearArticulo = new javax.swing.JMenuItem();
        opVentas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opHacerVenta = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        opReporteVendedor = new javax.swing.JMenuItem();
        opReporteCliente = new javax.swing.JMenuItem();
        opReporteTotal = new javax.swing.JMenuItem();
        opInventario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpPrincipalLayout = new javax.swing.GroupLayout(dpPrincipal);
        dpPrincipal.setLayout(dpPrincipalLayout);
        dpPrincipalLayout.setHorizontalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        dpPrincipalLayout.setVerticalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );

        Administrar.setText("Administrar");

        opCrearUsuario.setText("Usuarios");
        opCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCrearUsuarioActionPerformed(evt);
            }
        });
        Administrar.add(opCrearUsuario);

        opCrearCliente.setText("Clientes");
        opCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCrearClienteActionPerformed(evt);
            }
        });
        Administrar.add(opCrearCliente);

        opCrearArticulo.setText("Articulos");
        opCrearArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCrearArticuloActionPerformed(evt);
            }
        });
        Administrar.add(opCrearArticulo);

        opVentas.setText("Ventas");
        opVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opVentasActionPerformed(evt);
            }
        });
        Administrar.add(opVentas);

        jMenuBar1.add(Administrar);

        jMenu2.setText("Venta");

        opHacerVenta.setText("Hacer venta");
        opHacerVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opHacerVentaActionPerformed(evt);
            }
        });
        jMenu2.add(opHacerVenta);

        jMenuBar1.add(jMenu2);

        Reportes.setText("Reportes");

        opReporteVendedor.setText("Reporte por vendedor");
        opReporteVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opReporteVendedorActionPerformed(evt);
            }
        });
        Reportes.add(opReporteVendedor);

        opReporteCliente.setText("Reporte por cliente");
        opReporteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opReporteClienteActionPerformed(evt);
            }
        });
        Reportes.add(opReporteCliente);

        opReporteTotal.setText("Reporte ventas totales");
        opReporteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opReporteTotalActionPerformed(evt);
            }
        });
        Reportes.add(opReporteTotal);

        opInventario.setText("Inventario total");
        opInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opInventarioActionPerformed(evt);
            }
        });
        Reportes.add(opInventario);

        jMenuBar1.add(Reportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCrearClienteActionPerformed
        // TODO add your handling code here:
        frmCliente frmCliente = new frmCliente();
        dpPrincipal.add(frmCliente);
        frmCliente.show();
        
    }//GEN-LAST:event_opCrearClienteActionPerformed

    private void opCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCrearUsuarioActionPerformed
        // TODO add your handling code here:
        frmUsuario frmUsuario = new frmUsuario();
        dpPrincipal.add(frmUsuario);
        frmUsuario.show();
        
        
    }//GEN-LAST:event_opCrearUsuarioActionPerformed

    private void opReporteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opReporteTotalActionPerformed
        frmVentasTotales frmVentasTotales = new frmVentasTotales();
        dpPrincipal.add(frmVentasTotales);
        frmVentasTotales.show();
    }//GEN-LAST:event_opReporteTotalActionPerformed

    private void opCrearArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCrearArticuloActionPerformed
        // TODO add your handling code here:
        frmArticulo frmArticulo = new frmArticulo();
        dpPrincipal.add(frmArticulo);
        frmArticulo.show();
    }//GEN-LAST:event_opCrearArticuloActionPerformed

    private void opHacerVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opHacerVentaActionPerformed
        frmVenta frmVenta = new frmVenta();
        dpPrincipal.add(frmVenta);
        frmVenta.show();
            
    }//GEN-LAST:event_opHacerVentaActionPerformed

    private void opReporteVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opReporteVendedorActionPerformed
        frmReporteVendedor frmReporteVendedor = new frmReporteVendedor();
        dpPrincipal.add(frmReporteVendedor);
        frmReporteVendedor.show();
    }//GEN-LAST:event_opReporteVendedorActionPerformed

    private void opReporteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opReporteClienteActionPerformed
        frmReporteCliente frmReporteCliente = new frmReporteCliente();
        dpPrincipal.add(frmReporteCliente);
        frmReporteCliente.show();
    }//GEN-LAST:event_opReporteClienteActionPerformed

    private void opInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opInventarioActionPerformed
       frmInventario frmInventario = new frmInventario();
       dpPrincipal.add(frmInventario);
       frmInventario.show();


    }//GEN-LAST:event_opInventarioActionPerformed

    private void opVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opVentasActionPerformed
      frmUDVentas frmUDVentas = new frmUDVentas();
      dpPrincipal.add(frmUDVentas);
      frmUDVentas.show();
    }//GEN-LAST:event_opVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  try {
        UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
    } catch (Exception ex) {
     
    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Administrar;
    private javax.swing.JMenu Reportes;
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opCrearArticulo;
    private javax.swing.JMenuItem opCrearCliente;
    private javax.swing.JMenuItem opCrearUsuario;
    private javax.swing.JMenuItem opHacerVenta;
    private javax.swing.JMenuItem opInventario;
    private javax.swing.JMenuItem opReporteCliente;
    private javax.swing.JMenuItem opReporteTotal;
    private javax.swing.JMenuItem opReporteVendedor;
    private javax.swing.JMenuItem opVentas;
    // End of variables declaration//GEN-END:variables
}
