/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import entidades.cliente;
import entidades.empleados;
import entidades.venta;
import logica.logCalculos;
import logica.logCliente;
import logica.logVenta;
import logica.logicaEmpleados;

/**
 *
 * @author Allan
 */
public class frmUDVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUDVentas
     */
    public frmUDVentas() {
        initComponents();
        this.llenarComboBoxCliente();
        this.llenarComboBoxVendedor();
        this.completarTableModel();
        this.refrescarTabla();
        dtRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtRegistrosMouseClicked(evt);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtCedVendedor = new javax.swing.JTextField();
        txtCedCliente = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtRegistros = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        cbVendedor = new javax.swing.JComboBox<>();
        cbCliente = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar y eliminar ventas");

        jLabel1.setText("ID");

        jLabel2.setText("Vendedor");

        jLabel3.setText("Cliente");

        jLabel4.setText("Cedula del Cliente ");

        jLabel5.setText("Cedula del vendedorr");

        jLabel7.setText("Total");

        jLabel8.setText("Sub total");

        txtCedVendedor.setEditable(false);

        txtCedCliente.setEditable(false);

        txtTotal.setEditable(false);

        txtSubTotal.setEditable(false);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        dtRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "vendedor", "Cedula vendedor", "Cliente", "Cedula cliente", "Descuento", "Cantidad", "Sub Total", "Total"
            }
        ));
        jScrollPane1.setViewportView(dtRegistros);

        jLabel9.setText("Descuento ");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        cbVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVendedorActionPerformed(evt);
            }
        });

        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(78, 78, 78)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVendedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCedVendedor)
                            .addComponent(txtCedCliente)
                            .addComponent(txtTotal)
                            .addComponent(txtSubTotal)
                            .addComponent(txtDescuento)
                            .addComponent(cbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnCalcular)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscar)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnActualizar)
                                .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCedVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCedCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     void llenarComboBoxCliente(){
        logCliente logCliente = new logCliente();
        List<cliente> miLista = logCliente.todosClientes();
        for (int i = 0; i < miLista.size(); i++) {
           cbCliente.addItem(miLista.get(i).getNombre()+" "+miLista.get(i).getApellidos());
      }
    }
    void llenarComboBoxVendedor(){
        logicaEmpleados logicaEmpleados =  new logicaEmpleados();
        List<empleados> miLista = logicaEmpleados.todosEmpleados();
        for (int i = 0; i < miLista.size(); i++) {
            cbVendedor.addItem(miLista.get(i).getNombre()+" "+miLista.get(i).getApellidos());          
        }
    }

    private void refrescarTabla(){
        TableModel tablaModel = this.completarTableModel();
        dtRegistros.setModel(tablaModel);
    }
    private TableModel completarTableModel(){
        try {
            logVenta logVenta = new logVenta();
            List<venta> miLista = logVenta.todoVentas();
            Object[] columnas = new Object[]{"ID", "Vendedor", "Cedula vendedor","Cliente","Cedula cliente","Descuento", "Cantidad", "SubTotal","Total"};
            Object[][] datos = new Object[miLista.size()][columnas.length];
            for (int i = 0; i < miLista.size(); i++) {
                datos[i][0] = miLista.get(i).getId();
                datos[i][1] = miLista.get(i).getVendedor();
                datos[i][2] = miLista.get(i).getCedVendedor();
                datos[i][3] = miLista.get(i).getCliente();
                datos[i][4] = miLista.get(i).getCedCliente();
                datos[i][5] = miLista.get(i).getDescuento();
                datos[i][6] = miLista.get(i).getCantidad();
                datos[i][7] = miLista.get(i).getTotal();
                datos[i][8] = miLista.get(i).getSubTotal();

            }

            
            DefaultTableModel model = new DefaultTableModel(datos, columnas);
            return model;
        } catch (Exception e) {
            System.out.println(e);
        }
        return null;
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe ingresar un id", "Falta informacion", JOptionPane.WARNING_MESSAGE);
        } else {
            logVenta logVenta = new logVenta();
            venta venta = new venta();
            venta = logVenta.obtenerVenta(Integer.parseInt(txtID.getText()));
            if (venta==null) {
                JOptionPane.showMessageDialog(new JFrame(), "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                txtTotal.setText(String.valueOf(venta.getTotal()));
                txtDescuento.setText(String.valueOf(venta.getDescuento()));
                txtSubTotal.setText(String.valueOf(venta.getSubTotal()));               
                System.out.println("aaqaaa");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (txtID.getText().isEmpty()||txtDescuento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe llenar todos los campos", "Falta informacion", JOptionPane.WARNING_MESSAGE);
        } else {
            venta venta = new venta();
            logVenta logVenta = new logVenta();
            venta.setId(Integer.parseInt(txtID.getText()));
            venta.setVendedor(String.valueOf(cbVendedor.getSelectedItem()));
            venta.setCedVendedor(txtCedVendedor.getText());
            venta.setCliente(String.valueOf(cbCliente.getSelectedItem()));
            venta.setCedCliente(txtCedCliente.getText());
            venta.setDescuento(Integer.parseInt(txtDescuento.getText()));
            venta.setSubTotal(Double.parseDouble(txtSubTotal.getText()));
            if (logVenta.actualizarVenta(venta)) {
                JOptionPane.showMessageDialog(new JFrame(), "Se actualizo correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                this.refrescarTabla();
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        logVenta logVenta = new logVenta();
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe ingresar un id", "Falta informacion", JOptionPane.WARNING_MESSAGE);
        } else {
            if (logVenta.eliminarVenta(Integer.parseInt(txtID.getText()))) {
                JOptionPane.showMessageDialog(new JFrame(), "Se elimino correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                this.refrescarTabla();
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
         if (txtDescuento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Debe ingresar un descuento", "Falta informacion", JOptionPane.WARNING_MESSAGE);
        } else {
             logCalculos logCalculos = new logCalculos();
            txtSubTotal.setText(String.valueOf(logCalculos.calcularDescuento(Double.parseDouble(txtTotal.getText()), Integer.parseInt(txtDescuento.getText()))));
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cbVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVendedorActionPerformed
        logicaEmpleados logicaEmpleados =  new logicaEmpleados();
        List<empleados> miLista = logicaEmpleados.todosEmpleados();
        txtCedVendedor.setText(miLista.get(cbVendedor.getSelectedIndex()).getCedula());
    }//GEN-LAST:event_cbVendedorActionPerformed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        logCliente logCliente = new logCliente();
        List<cliente> miLista = logCliente.todosClientes();
        txtCedCliente.setText(miLista.get(cbCliente.getSelectedIndex()).getCedula());
    }//GEN-LAST:event_cbClienteActionPerformed
    private void dtRegistrosMouseClicked(java.awt.event.MouseEvent evt) {                                         
        this.mousePressed();
    }  
    private void mousePressed(){
        txtID.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),0).toString());
        txtTotal.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),7).toString());
        txtDescuento.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),5).toString());
        txtSubTotal.setText(dtRegistros.getValueAt(dtRegistros.getSelectedRow(),8).toString());


    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbVendedor;
    private javax.swing.JTable dtRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCedCliente;
    private javax.swing.JTextField txtCedVendedor;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
